EMAIL_HOST="mails.vu.nl"
EMAIL_HOST_USER="CHANGE_ME"
EMAIL_HOST_PASSWORD="CHANGE_ME"
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_SENDER = "laurens.rietveld@vu.nl"
EMAIL_ANOUNCEMENT_RECIPIENTS = ['wai-meetings@few.vu.nl', 'laurens.rietveld@vu.nl']
EMAIL_REQUEST_ABSTRACT_CC = ['laurens.rietveld@vu.nl']
EMAIL_FOOTER = "Best, Laurens and Chris"
